version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.8.1
    links:
      - dispatcher:dispatcher
    environment:
      DEFAULT_ACCESS_CONTROL_ALLOW_ORIGIN_HEADER: "*"
  dispatcher:
    image: semtech/mu-dispatcher:latest
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./data/db/virtuoso.ini:/data/virtuoso.ini
  migrations:
    restart: always
    image: semtech/mu-migrations-service
    links:
      - db:database
    volumes:
      - ./config/migrations:/data/migrations
  resource:
    image: semtech/mu-cl-resources:1.20.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
  frontend:
    image: lblod/frontend-mow-registry:feature-docker-build
